#%RAML 1.0
title: warn-api
version: v1
baseUri: http://www.opendoxie.com

types:
  LayoffEvent:
    type: object
    properties:
      id: string
      company: string
      number-affected: number
      effective-date: string
      state: string
      county:
        type: string
        required: false
      city:
        type: string
        required: false
      notes:
        type: string
        required: false
      source:
        type: string

/events:
  post:
    responses:
      200:
        body:
          application/json:
            type: LayoffEvent
            example: |
              {
                "id": "b9fb701b3578d39811844a11de3c58a6",
                "company": "Dunder Mifflin, Inc.",
                "number-affected": 63,
                "effective-date" : "May 16th, 2013",
                "state": "PA",
                "county": "Lacawanna",
                "city": "Scranton",
                "notes": "closed after 13 seasons",
                "source": "PAWARNnotices2013.xls"
              }
  get:
    queryParameters:
      company:
        type: string
        required: false
        example: "Dunder Miflin LLC"
      location:
          type: string
          required: false
          example: "Scranton, PA"
      state:
        type: string
        required: false
        example: "PA"
      sort-by:
        description: One of "date", "affected", "relevance"
        type: string
        required: false
        default: "relevance"
      limit:
        type: integer
        required: false
        default: 10
      offset:
        type: integer
        required: false
        default: 0

    responses:
      200:
        body:
          application/json:
            type: array
            items: LayoffEvent
  /id:
    get:
      responses:
        200:
          body:
            application/json:
              type: LayoffEvent
