#
# Application stack
# 

## TODO


#
# Application DB stack
#
db:
  image: mongo:3.2
  ports:
    - 27017:27017
  volumes:
    - ./mongo-data:/data/db
elasticsearch:
  image: elasticsearch:2.3
  ports:
    - 9200:9200
    - 9300:9300
  volumes:
    - ./es-data:/usr/share/elasticsearch/data
kibana:
  image: kibana:latest
  ports:
    - 5601:5601
  links:
    - elasticsearch:elasticsearch

#
# Log manager: ELK Stack
#
logger:
  image: sebp/elk
  volumes:  
    - ./logger-data:/var/lib/elasticsearch
  ports:
    - "5602:5601"
    - "9201:9200"
    - "5044:5044"
    - "5000:5000"

